apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::533144716022:role/eksctl-simple-jwt-api2-nodegroup-NodeInstanceRole-1ILTAE2JC1ZW8
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::533144716022:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-24T08:35:42Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1198"
  uid: 8791e108-f25b-438e-a7a2-b51e87133d76
